version: "3.9"

services:
  postgres:
    image: postgres:15-alpine
    container_name: dev-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: booking
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d booking"]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: dev-redis
    ports: ["6379:6379"]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.105.0
    container_name: dev-otelcol
    command: ["--config=/etc/otelcol-config.yml"]
    volumes:
      - ./otel/otelcol-config.yml:/etc/otelcol-config.yml:ro
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
      - "8889:8889"   # Prometheus exporter (optional)

  jaeger:
    image: jaegertracing/all-in-one:1.56
    container_name: dev-jaeger
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686" # UI
      - "14250:14250" # OTLP gRPC
      - "14268:14268"

volumes:
  pgdata:
